[2024-11-17T14:25:57.780+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: currency_exchange_pipeline.currency_exchange_extraction manual__2024-11-17T14:25:03.356647+00:00 [queued]>
[2024-11-17T14:25:57.804+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: currency_exchange_pipeline.currency_exchange_extraction manual__2024-11-17T14:25:03.356647+00:00 [queued]>
[2024-11-17T14:25:57.805+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-17T14:25:57.838+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): currency_exchange_extraction> on 2024-11-17 14:25:03.356647+00:00
[2024-11-17T14:25:57.849+0000] {standard_task_runner.py:57} INFO - Started process 40 to run task
[2024-11-17T14:25:57.858+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'currency_exchange_pipeline', 'currency_exchange_extraction', 'manual__2024-11-17T14:25:03.356647+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/currency_exchange_dag.py', '--cfg-path', '/tmp/tmpa8aaoprv']
[2024-11-17T14:25:57.864+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask currency_exchange_extraction
[2024-11-17T14:25:57.990+0000] {task_command.py:416} INFO - Running <TaskInstance: currency_exchange_pipeline.currency_exchange_extraction manual__2024-11-17T14:25:03.356647+00:00 [running]> on host ca54fda2bb7e
[2024-11-17T14:25:58.188+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Azeem' AIRFLOW_CTX_DAG_ID='currency_exchange_pipeline' AIRFLOW_CTX_TASK_ID='currency_exchange_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T14:25:03.356647+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T14:25:03.356647+00:00'
[2024-11-17T14:25:58.195+0000] {logging_mixin.py:151} INFO - Error fetching exchange rates: No connection adapters were found for '"https://api.exchangeratesapi.io/v1/latest"'
[2024-11-17T14:25:58.244+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-17T14:25:58.318+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
